version: 1
formatters:
  access:
    format: '%(asctime)s %(levelname)s: %(client_addr)s - "%(request_line)s" %(status_code)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  default:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout
loggers:
  uvicorn.access:
    handlers: [default]
    level: INFO
    propagate: no 